-- BATCH

DROP TABLE TB_CO_BATCH ; 
CREATE TABLE TB_CO_BATCH (
	BATCH_ID			VARCHAR(30)        NOT NULL , 
	BATCH_NM			VARCHAR(200)			NULL,
  	BATCH_DC			VARCHAR(1000)			NULL,   	
  	JOB_EXECUT 			VARCHAR(4000)			NULL,   	
  	JOB_PARAM 			VARCHAR(100)			NULL,   	
  	JOB_SE_CD_ID		VARCHAR(30)			NULL,  
	JOB_PD_CD_ID		VARCHAR(30)			NULL,  
	JOB_BGNDE			VARCHAR(8)        		NULL,
	JOB_ENDDE			VARCHAR(8)        		NULL, 
	JOB_CYCLE_CD_ID		VARCHAR(30)			NULL, 	
	UNITY_ID			VARCHAR(100)			NULL,  
	SCEN_ID				VARCHAR(30)			NULL,  
	SCEN_NM				VARCHAR(200)			NULL, 
	PRECDNG_AT			VARCHAR(1)				NULL, 
	USE_AT				VARCHAR(1)				NULL, 
  	RGS_DT				DATE					NULL,
  	RGS_USER_ID			VARCHAR(30)			NULL,
  	UPD_DT				DATE					NULL,
  	UPD_USER_ID			VARCHAR(30)			NULL ,
  	PRIMARY KEY(BATCH_ID)
);
DROP TABLE TB_CO_BATCH_JOB ; 
CREATE TABLE TB_CO_BATCH_JOB (
	BATCH_ID			VARCHAR(30)        	NOT NULL , 
	JOB_SN				NUMERIC(10)				NOT	NULL,
	JOB_DE				VARCHAR(8)					NULL, 
	JOB_WEEK        	VARCHAR(1)					NULL, 
   	JOB_MONTH        	VARCHAR(2)					NULL, 
   	JOB_DAY          	VARCHAR(2)					NULL, 
   	JOB_HOUR         	VARCHAR(2)					NULL, 
   	JOB_MINUTE			VARCHAR(2)					NULL,
   	PRIMARY KEY(BATCH_ID , JOB_SN)
);
DROP TABLE TB_CO_BATCH_RESULT;
CREATE TABLE TB_CO_BATCH_RESULT (
	BATCH_ID			VARCHAR(30)        NOT NULL,
    RESULT_SN			NUMERIC(10)			NOT NULL,
    BATCH_NM			VARCHAR(200)			NULL,
	BATCH_BGNDT			VARCHAR(23)			NULL,
	BATCH_ENDDT			VARCHAR(23)			NULL,
	RESULT_STTUS_CD_ID	VARCHAR(30)			NULL,	
	RESULT_MSG			VARCHAR(4000)			NULL,	
	RGS_DT				DATE					NULL,
	JOB_SN				NUMERIC(10)				NULL,
	BATCH_EXC_CD_ID		VARCHAR(30)			NULL, 
	PRIMARY KEY(BATCH_ID , RESULT_SN)
);

-- MyDaemon
DROP TABLE TB_MY_DAEMON;
CREATE TABLE TB_MY_DAEMON(
	DAEMON_ID 		VARCHAR(30) 	NOT NULL , 
	DAEMON_NM 		VARCHAR(100)	NOT NULL , 
	DAEMON_TEXT 	VARCHAR(1000) 	NULL , 
	CONTROLLER_NM 	VARCHAR(100)	NOT NULL , 
	DAEMON_PARAM    VARCHAR(1000)   NULL , 
	INTERVAL_AT		VARCHAR(1)      NOT NULL , 
	MINUTE			VARCHAR(1000)   NOT NULL , 
	BGNDE			VARCHAR(8)		NOT NULL , 
	ENDDE			VARCHAR(8)		NOT NULL ,
	USE_AT			VARCHAR(1)      NOT NULL ,
	DEL_AT			VARCHAR(1)      NOT NULL ,
	PRIMARY KEY ( DAEMON_ID )
) ; 

DROP TABLE TB_MY_DAEMON_LOG ;
CREATE TABLE TB_MY_DAEMON_LOG (
	DAEMON_ID VARCHAR(30) NOT NULL , 
    SORT_SN VARCHAR(30) NOT NULL ,
    START_DT TIMESTAMP NULL ,
    END_DT TIMESTAMP NULL , 
    SUCC_AT VARCHAR(1) NOT NULL ,
    MESSAGE VARCHAR(4000) NULL ,
    PRIMARY KEY(DAEMON_ID , SORT_SN)
) ; 


COMMIT;

