INSERT INTO TB_CO_BATCH (BATCH_ID, JOB_EXECUT, JOB_PARAM, JOB_SE_CD_ID, JOB_PD_CD_ID, JOB_BGNDE, JOB_ENDDE, JOB_CYCLE_CD_ID, USE_AT, BATCH_NM, BATCH_DC)
VALUES ('COM_00001', 'testController', NULL, '매번', '영구', NULL, NULL, '분단위', 'Y', 'test', 'test');

INSERT INTO TB_CO_BATCH_JOB (BATCH_ID, JOB_SN, JOB_DE, JOB_WEEK, JOB_MONTH, JOB_DAY, JOB_HOUR, JOB_MINUTE)
VALUES('COM_00001', 1, NULL, NULL, NULL,NULL, '00', '1');



DROP TABLE TB_CO_TEST ; 
CREATE TABLE TB_CO_TEST (
	UUID VARCHAR(30)  , 
    TEXT VARCHAR(1000)  ,
    PRIMARY KEY (UUID)
) ; 

INSERT INTO TB_CO_TEST VALUES ( '1' , '1') ;
INSERT INTO TB_CO_TEST VALUES ( '2' , '2') ;