DROP TABLE TB_VIDEO_INGEST ; 
CREATE TABLE TB_VIDEO_INGEST (
	SUPER_INGEST_ID VARCHAR(30) NOT NULL ,
	INGEST_ID VARCHAR(30) NOT NULL ,
    INGEST_NM VARCHAR(1000) NOT NULL , 
    INGEST_TEXT VARCHAR(4000) NULL , 
    INGEST_REAL_PATH VARCHAR(1000) NOT NULL ,
    USE_AT VARCHAR(1) DEFAULT 'Y' ,
    DEL_AT VARCHAR(1) DEFAULT 'N' ,
    PRIMARY KEY(SUPER_INGEST_ID,  INGEST_ID)
);

DROP TABLE TB_VIDEO_SUPER ; 
CREATE TABLE TB_VIDEO_SUPER (
	VIDEO_SUPER_ID VARCHAR(30) NOT NULL ,
    VIDEO_SUPER_NM VARCHAR(1000) NOT NULL , 
    VIDEO_SUPER_EXPLAIN VARCHAR(4000) NULL ,
    VIDEO_SUPER_ACTOR VARCHAR(1000) NULL , 
    VIDEO_SUPER_GENRE VARCHAR(1000) NULL , 
    VIDEO_SUPER_MAIN_IMAGE VARCHAR(100) NULL ,
    
    USE_AT VARCHAR(1) DEFAULT 'Y' ,
    DEL_AT VARCHAR(1) DEFAULT 'N' ,
    PRIMARY KEY(VIDEO_SUPER_ID)
    
);

DROP TABLE TB_VIDEO ; 
CREATE TABLE TB_VIDEO (
	VIDEO_SUPER_ID VARCHAR(30) NOT NULL ,
	VIDEO_ID VARCHAR(30) NOT NULL ,
    VIDEO_NM VARCHAR(1000) NOT NULL , 
    VIDEO_EXPLAIN VARCHAR(4000) NULL ,
    VIDEO_ACTOR VARCHAR(1000) NULL , 
    VIDEO_PLAY_PATH VARCHAR(1000) NOT NULL ,
    VIDEO_REAL_PATH VARCHAR(1000) NOT NULL ,
    USE_AT VARCHAR(1) DEFAULT 'Y' ,
    DEL_AT VARCHAR(1) DEFAULT 'N' ,
    PRIMARY KEY(VIDEO_SUPER_ID,  VIDEO_ID)
);


DROP TABLE TB_CONTENTS;
CREATE TABLE TB_CONTENTS(
	CONTENTS_ID VARCHAR(30) NOT NULL , 
	CONTENTS_NM VARCHAR(1000) NOT NULL , 
	
	USE_AT VARCHAR(1) DEFAULT 'Y' ,
    DEL_AT VARCHAR(1) DEFAULT 'N' ,
	
	PRIMARY KEY(CONTENTS_ID)
);

DROP TABLE TB_CONTENTS_LIST;
CREATE TABLE TB_CONTENTS_LIST (
	CONTENTS_ID VARCHAR(30) NOT NULL , 
	VIDEO_SUPER_ID VARCHAR(30) NOT NULL ,
	SORT_SN VARCHAR(10) NOT NULL , 
    
	PRIMARY KEY(CONTENTS_ID, VIDEO_SUPER_ID)
);

DROP TABLE TB_IMAGE;
CREATE TABLE TB_IMAGE (
	IMAGE_ID VARCHAR(30) PRIMARY KEY, 
    IMAGE_NM VARCHAR(100) , 
    IMAGE_FILE_NM VARCHAR(100)    
);
